### ISSUE TITLE
Object reference not found issue

### ISSUE THREAD

**Issue by brainplant** [MLogdberg/APIManagementARMTemplateCreator#10]
Aggregation exception thrown, se following exceptions for more information
Exception: Object reference not set to an instance of an object.
   at APIManagementTemplate.TemplateGenerator.<GenerateTemplate>d__11.MoveNext() in C:\Users\Admin\Source\Repos\APIManagementARMTemplateCreator2\APIManagementTemplate\TemplateGenerator.cs:line 141
-------------------------------------------

I have fixed this issue in my branch https://github.com/brainplant/APIManagementARMTemplateCreator .See if it can merged  to master.

**Comment by brainplant** [comment]
Line number is  140 of TemplateGenerator .cs
![image](https://user-images.githubusercontent.com/12545725/43722756-ef6cc7f2-998d-11e8-9cf9-40f2b7565533.png)

needs to be changed to 

![image](https://user-images.githubusercontent.com/12545725/43722809-0cf93742-998e-11e8-92c2-aa8b924fda23.png)

**Comment by MLogdberg** [comment]
ahh yea but that wont fix it to 100%, since it sometimes is Mnaual and sometime Request (depding on the template choosen when creating the Logic App) think I'll just change it to "invoke_" meanwhile and then need to get a better solution for it.

**Comment by MLogdberg** [comment]
This should be fixed in the last update, now even custom triggers are supported.
