### ISSUE TITLE
Backends with Custom URL causes NullReferenceException

### ISSUE THREAD

**Issue by twinpiloot** [MLogdberg/APIManagementARMTemplateCreator#100]
If you have defined a backend with a custom URL, the template generator causes a NullReferenceException. Currently, the template generator expects a Logic App or Function App, not a custom URL.

**Comment by MLogdberg** [comment]
Hi! this should be solved in PR #102 Thanks for reporting in and issue!

**Comment by twinpiloot** [comment]
I tested the fix and it works. Thanks for solving this Mattias!
