### ISSUE TITLE
Add logger support

### ISSUE THREAD

**Issue by joeyeng** [MLogdberg/APIManagementARMTemplateCreator#11]
It would be great if there were logger support to App Insights. Here's an example of how we've done it:

```JSON
{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "api-name": {
            "type": "string",
            "minLength": 1
        },
        "instrumentationKey": {
            "type": "string",
            "minLength": 1
        },
        "subscription": {
            "defaultValue": "dev",
            "type": "string",
            "allowedValues": [
                "sandbox",
                "dev",
                "test",
                "production"
            ]
        }
    },
    "variables": {
        "api-logger-name": "[concat(parameters('api-name'), '-', parameters('subscription'), '-logger')]",
        "apiM-name": "[concat('apiManagement-', parameters('subscription'), '-apimanager')]",
        "instrumentationKey": "[parameters('instrumentationKey')]"
    },
    "resources": [

// LOGGER
        {
            "type": "Microsoft.ApiManagement/service/loggers",
            "name": "[concat(variables('apiM-name'), '/', variables('api-logger-name'))]",
            "apiVersion": "2018-06-01-preview",
            "tags": {
                "displayName": "logger"
            },
            "properties": {
                "loggerType": "applicationInsights",
                "credentials": {
                    "instrumentationKey": "[variables('instrumentationKey')]"
                },
                "isBuffered": true
            }
        },

// API
        {
            "type": "Microsoft.ApiManagement/service/apis",
            "name": "api-name",
            "apiVersion": "2018-01-01",
            "properties": {
            },
            "resources": [

// LOGGER ASSOCIATION WITH API
                {
                    "name": "applicationinsights",
                    "type": "diagnostics",
                    "apiVersion": "2018-06-01-preview",
                    "properties": {
                        "enabled": true,
                        "loggerId": "[resourceId('Microsoft.ApiManagement/service/loggers', variables('apiM-name'), variables('api-logger-name'))]"
                    },
                    "resources": [],
                    "dependsOn": [
                        "[resourceId('Microsoft.ApiManagement/service/apis', variables('apiM-name'), variables('api-v1-name'))]"
                    ]
                }
            ]
        }
    ]
}
```

Hopefully I got that right. I combined two different templates we had and tried to clean it up to show the relevant parts.

**Comment by MLogdberg** [comment]
Good idea, I'll try to get that with next release

**Comment by nilshedstrom** [comment]
Logger support was included in pull request #24. Is that enough?
It does not create new loggers but will create a "link" to existing ones.

**Comment by MLogdberg** [comment]
Guess this will be enough for now?

**Comment by joeyeng** [comment]
It'd be nice if this was part of the tool, but creating the link is fine for us. However, I just tested this out (with commit f17cb077f29521815da11d087ad9ff531485da20) and it didn't seem to generate the logger link for an API with an existing logger.

**Comment by joeyeng** [comment]
Hi @nilshedstrom, maybe I'm misunderstanding what you meant when you said creating a link to an existing logger. I'm expecting something similar to what I have at the bottom of my sample template (LOGGER ASSOCIATION WITH API). I just pulled latest and reran the tool against an API that has an App Insights logger configured, but I'm not seeing any "link" it in the output. Am I missing a parameter?

**Comment by nilshedstrom** [comment]
Pull request 32 is not merged yet so you dont get it by pulling the latest version of the main branch.

When you get it and have the CreateApplicationInsightsInstance as $true then you will get something like this in resources for the APIM instance

 {
          "type": "Microsoft.Insights/components",
          "name": "[parameters('apimServiceName_applicationInsights')]",
          "apiVersion": "2015-05-01",
          "properties": {
            "Application_Type": "other"
          },
          "resources": [],
          "dependsOn": [
            "[resourceId('Microsoft.ApiManagement/service', parameters('apimServiceName'))]"
          ],
          "location": "[parameters('apimServiceName_location')]",
          "kind": "other"
        },
        {
          "type": "Microsoft.ApiManagement/service/loggers",
          "name": "[concat(parameters('apimServiceName'),'/',parameters('apimServiceName_applicationInsights'))]",
          "apiVersion": "2017-03-01",
          "properties": {
            "loggerType": "applicationInsights",
            "description": null,
            "credentials": {
              "instrumentationKey": "[reference(resourceId('Microsoft.Insights/components', parameters('apimServiceName_applicationInsights')), '2014-04-01').InstrumentationKey]"
            },
            "isBuffered": true
          },
          "resources": [],
          "dependsOn": [
            "[resourceId('Microsoft.ApiManagement/service', parameters('apimServiceName'))]",
            "[resourceId('Microsoft.Insights/components',parameters('apimServiceName_applicationInsights'))]"
          ]
        }

**Comment by joeyeng** [comment]
This will create the logger and the app insights instance, but you need to add a diagnostics resource to assign the logger to the API.

**Comment by nilshedstrom** [comment]
@joeyeng Loggers are created, diagnostics resources are created and Application Insights resources can be created if requested. What else is needed before this issue can be closed?

**Comment by joeyeng** [comment]
Great, I will close this issue now.
