### ISSUE TITLE
Extracting and Deploying API Revisions

### ISSUE THREAD

**Issue by derekweber** [MLogdberg/APIManagementARMTemplateCreator#12]
When extracting an API with revisions, I see only resource metadata for the latest revision in the template file created. As all of the API resources are revision specific, I would expect to see resource definitions for both of my API revisions. Related to this, I can't seem to deploy my revision to a different resource group with the template created. There is an error that the operation already exists, even though it is deploying revision 2. Are API revisions generally not supported for ARM? I have searched extensively, but am unable to find any documentation that pertains to this use case.

**Comment by MLogdberg** [comment]
Hi, I've actually never tried this. But I'll test and see what I can find.

**Comment by MLogdberg** [comment]
Just adding a bump and must admit I haven't had the time yet to test this. Still on the todo list though.

**Comment by derekweber** [comment]
Much appreciated. Could just be a limitation of ARM. Interested to see what you may learn.

**Comment by nilshedstrom** [comment]
In the current REST API you can only list revisions not create them
https://docs.microsoft.com/en-us/rest/api/apimanagement/apirevisions/list

If it is not possible to do it in the REST API then there is no way you can do it in ARM.

**Comment by derekweber** [comment]
Aha. Thank you very much, @nilshedstrom . Hopefully this is added one day, as it would be extremely useful.
