### ISSUE TITLE
Get-APIManagementTemplate stopped working for Consumption instances

### ISSUE THREAD

**Issue by jjohnsen** [MLogdberg/APIManagementARMTemplateCreator#123]
Hi,

Running with the following parameters:

`Get-APIManagementTemplate `
    -APIFilters "name eq '$apiName'" `
    -Token $account.accessToken `
    -APIManagement $apimServiceName `
    -ResourceGroup $resourceGroup `
    -SubscriptionId $subscription `
    -ExportGroups $false `
    -ParametrizePropertiesOnly $true `
    -FixedServiceNameParameter $true `
    -DebugOutPutFolder 'debug'`

Failes with error:
`Get-APIManagementTemplate
Aggregation Exception thrown, One or more errors occurred. (Object reference not set to an instance of an object.), first Exception message is: Object reference not set to an instance of an object., for more information read the output file.`

The debug folder contains the following files:
* service-xxx.json
* service-xxx-policies.json
* service-xxx-identityProviders.json

service-xxx-identityProviders.json contains the following:
`{"error":{"code":"MethodNotAllowedInPricingTier","message":"Method not allowed in Consumption pricing tier","details":null}}`

I've added another APIM instance to the same resource group running Developer sku, and it works as expected.

**Comment by MLogdberg** [comment]
Hi,
Would recommend to not extract the apim instance if not needed, since it will take alot of unnecessary deployment power if you execute that every time. But the error was that there was no check on SKU before extracting identityproviders it's added in PR #124 .

**Comment by jjohnsen** [comment]
I can comfirm that it now works with the new release 👍
Thanks a lot for the quick fix!
