### ISSUE TITLE
Securestring should be null by default

### ISSUE THREAD

**Issue by riha** [MLogdberg/APIManagementARMTemplateCreator#15]
When exporting today the actual value from `Named values` are set as the defaultvalue of the property. This is not good by obvious reasons.

Would prefer if this instead was set to `null` in the export.

For example
```
 "Alerts-ResourceKey_value": {
      "type": "securestring",
      "defaultValue": "0VNs80QFoZuI4BEomZ1UnumLeYmUCGCXXXXXXXXX="
    },
```

**Comment by MLogdberg** [comment]
Good input, fixing this.

**Comment by MLogdberg** [comment]
This is not fixed and merged into master.

**Comment by MLogdberg** [comment]
This is now fixed.. sorry misspelled
