### ISSUE TITLE
Hardcoded api name in the api-product registration

### ISSUE THREAD

**Issue by joeyeng** [MLogdberg/APIManagementARMTemplateCreator#17]
Ran into another hardcoding issue for api-product registration that caused deployment to fail.

This is the name for the api-product registration:
`"[concat(parameters('service_apim_name'), '/', parameters('product_name'), '/HARDCODED_API_NAME')]"`

The name of the api at the end should be parameterized.

I'll get started on a PR for this.

**Comment by MLogdberg** [comment]
Thanks for adding aPR, forgott to close this issue.
