### ISSUE TITLE
Listsecret for function key wrong operation name?

### ISSUE THREAD

**Issue by joeyeng** [MLogdberg/APIManagementARMTemplateCreator#19]
Hi @MLogdberg,

So you know when you import a function app as an api it will generate some code for the operation name (e.g. 5b16e9ec2c99226c5c42d98e)? The tool is using these codes for the operation name in the listsecret function call. Shouldn't it be the actual function app operation name, not these APIM codes that the function app doesn't know anything about?

Example:
`[listsecrets(resourceId(parameters('FunctionApp_funcappname_resourceGroup'),'Microsoft.Web/sites/functions', parameters('FunctionApp_funcappname_siteName'), '5b16e9ec2c99226c5c42d98e'),'2015-08-01').key]`

**Comment by MLogdberg** [comment]
Hi,
This is to reduce the number of parameters that are not providing a value to be changed, maybe it should be possible to change? I've never changed it between environments but if this is something that is used we should add this. What do you think?

**Comment by joeyeng** [comment]
Well, for us the listsecrets call fails, because 5b16e9ec2c99226c5c42d98e doesn't exist as a resource of the function. So we had to update the template after it was generated by the tool by parameterizing the operation names. Example: parameters['operation_5b16e9ec2c99226c5c42d98e']

Btw, it looks like the way operation names are generated by APIM has changed from the code to: {http-verb}-{display-name-without-spaces}

**Comment by joeyeng** [comment]
Closing this since this isnt default function import behavior anymore.
