### ISSUE TITLE
Support for new function app import functionality

### ISSUE THREAD

**Issue by joeyeng** [MLogdberg/APIManagementARMTemplateCreator#22]
The the new APIM import functionality for function apps no longer uses rewrite-uri policies to set the function key querystring. The function key is now stored in a backends resource:

``` JSON
{
      "comments": "Generated for resource /subscriptions/ABC/resourceGroups/apimanagement-dev-resourcegroup/providers/Microsoft.ApiManagement/service/apim/backends/function",
      "type": "Microsoft.ApiManagement/service/backends",
      "name": "[concat(parameters('service_apim_name'), '/' ,'function')]",
      "apiVersion": "2017-03-01",
      "properties": {
        "title": null,
        "description": "[parameters('function_siteName')]",
        "url": "[concat('https://',toLower(parameters('function_siteName')),'.azurewebsites.net/')]",
        "protocol": "http",
        "resourceId": "[concat('https://management.azure.com/','subscriptions/',subscription().subscriptionId,'/resourceGroups/',parameters('function_resourceGroup'),'/providers/Microsoft.Web/sites/',parameters('function_siteName'))]",
        "credentials": {
          "query": {
            "code": [
              "{{function-key}}"
            ]
          }
        }
      },
      "resources": [],
      "dependsOn": []
    }
```

The tool needs to add a property for the {{function-key}} referenced by the backend.

**Comment by MLogdberg** [comment]
Thanks for adding this issue, I'll get started to sort this out.

**Comment by joeyeng** [comment]
It appears this may have been addressed by PR #27 and/or related PRs. @nilshedstrom, can you confirm?

**Comment by joeyeng** [comment]
I haven't done thorough testing on this change, but for a function app with multiple functions is it expected that the tool creates one backend resource or one for each function (with the associated function key)?

**Comment by nilshedstrom** [comment]
Yes. The property for the function-key should be added (see test TestServiceContainsPropertyForBackend in WithoutApiVersionSetIdTests).

In my Azure function-site I have two functions that are used by operations in my APIM instance.
The tool creates one backend for the Azure function and the policies that uses my Azure Functions references that backend. 

If you use ReplaceListSecretsWithParameter=$true for Write-APIManagementTemplates then you should make sure that you specify a key that is valid for all functions (and not just one function). If you specify a key for just one function that backend will only work for that function.

**Comment by joeyeng** [comment]
Okay, here's how I have my parameters setup in order to generate templates for a single API:
armclient token subid | Get-APIManagementTemplate -APIManagement apm-name -ResourceGroup apim-rg -SubscriptionId subid -APIFilters "name eq 'api-name'" | Write-APIManagementTemplates -GenerateParameterFiles $true  -SeparatePolicyFile $true

It appears the backend properties get generated in service.template.json now instead of with their associated API. If that's the case it seems we're forced to run the tool against the entire APIM instance (all APIs) or service.template.json will be missing resources. It's much slower to do that, but more importantly it means I can't update a single API without deploying instance wide changes, which will make change management difficult and risky. service.template.json contains our portal certificate settings for example.

**Comment by nilshedstrom** [comment]
If you use ApiStandalone=$true then you can deploy one API.
