### ISSUE TITLE
Extract API version with Header based field

### ISSUE THREAD

**Issue by lmfmsilva** [MLogdberg/APIManagementARMTemplateCreator#25]
Is there a way to create an ARM template filtered to a specific API version in which the versioning identifier is based in header fields? 

Maybe a "-APIFilters" value?

**Comment by MLogdberg** [comment]
Hi, I got the same problem so I'll look into it. Thanks for sugesting!

**Comment by MLogdberg** [comment]
Now there is a new parameter -ApiVersion to do filtering based on version, gives you a possiblity to specify i.e. "v2".
