### ISSUE TITLE
Support for KeyVault

### ISSUE THREAD

**Issue by twinpiloot** [MLogdberg/APIManagementARMTemplateCreator#34]
In the latest version , properties marked "secret" get a default value of "secretvalue" instead of the actual value. This makes sense, but it means a manual step after deployment when this tool is used in a CI/CD pipeline (we use this tool for deployments from DEV to TEST).

A possible solution would be to use a KeyVault for secrets. But this requires 2 changes:
- An option to create a parameter file.
- An option to specify a KeyVault name.

**Comment by twinpiloot** [comment]
Meanwhile I've found another way of using KeyVault for secrets by just overriding the secrets with a parameter file.

**Comment by MLogdberg** [comment]
Added from the Logic App Template Creator part a cmdlet for generating Parmeter files with key vault dummy sample:

Get-ParameterTemplate -TemplateFile $filenname -KeyVault Static | Out-File $filennameparam
