### ISSUE TITLE
PolicyHandeAzureResources does not work correct

### ISSUE THREAD

**Issue by Geronius** [MLogdberg/APIManagementARMTemplateCreator#35]
PolicyHandeAzureResources depends on comment with is added when selecting a for example a Logic App. This comment is not added anymore. Please reengineer this logic

Comment what is missing looks like this:
` <!-- { "azureResource": { "type": "logicapp", "id": "/subscriptions/c107df29-a4af-4bc9-a733-f88f0eaa4296/resourceGroups/PreDemoTest/providers/Microsoft.Logic/workflows/INT001-GetOrderInfo/triggers/request" } } -->`

**Comment by MLogdberg** [comment]
Definitely, this need's to be addressed and is mostly there for backwards compability which might be overkill now.

**Comment by MLogdberg** [comment]
think we can close this now
