### ISSUE TITLE
Backend function key should be parameterized

### ISSUE THREAD

**Issue by joeyeng** [MLogdberg/APIManagementARMTemplateCreator#38]
Currently, the function key value is not getting parameterized for a backend. It's using listsecrets, which will fail because it can't be used to retrieve a host key. I have a PR fix for this. I have added this as an optional parameter (default false), because I don't want to assume this is how everyone will want to use it.

**Comment by joeyeng** [comment]
PR #39

**Comment by nilshedstrom** [comment]
Write-APIManagementTemplates have a parameter ReplaceListSecretsWithParameter does something similar
