### ISSUE TITLE
AzureResourceCollector returning resources with the wrong type

### ISSUE THREAD

**Issue by joeyeng** [MLogdberg/APIManagementARMTemplateCreator#45]
I just started getting this issue today. Here's an example. Resources of type "Microsoft.ApiManagement/service/apis/operations/policies" are coming back as "Microsoft.ApiManagement/service/apis/operations".

Can you confirm you're getting this or not?

**Comment by MLogdberg** [comment]
Hmm I need to check this up

**Comment by MLogdberg** [comment]
You are correct, the latest version is corrupt.

**Comment by joeyeng** [comment]
Thanks for confirming! Yes, forgot about name.

**Comment by joeyeng** [comment]
AzureResourceCollector.cs hasn't changed since August last year, so it must be a recent change on the Azure side.

**Comment by joeyeng** [comment]
For the REST API it looks like you have to retrieve an operation policy with the path /operation/{opid}/policies/policy instead of /operation/{opid}/policies (and looping through it).

**Comment by VitaliyKurokhtin** [comment]
This is a regression in recent APIM update. Fix is pending as soon as possible.

**Comment by joeyeng** [comment]
Thanks for the update.

**Comment by MLogdberg** [comment]
The problem is at the moment that the type returned is "one level to high" from the APIM REST Api when returned in lists.
So if we request for operations ie: _apis/{apiid}/operations_, the type returned of the items in the list is apis even if the json object is for operations.
If we request policies for an operation i.e _apis/{apiid}/operations/{opid}/policies_ the type returned of the items in the list is apis/operations even if the json object is for policies. 
I've asked the product team for info so let's see I'll come back with more information as soon as I have.

**Comment by VitaliyKurokhtin** [comment]
The fix for the issue is being rolled out now.

**Comment by joeyeng** [comment]
@VitaliyKurokhtin How long will it take to get rolled out? Still seeing issues.

**Comment by VitaliyKurokhtin** [comment]
May take till end of the day and early tomorrow. If you don't mind you could share your service name.

**Comment by MLogdberg** [comment]
Tested and at least one of the instances I have access to is working now as normal now.

**Comment by joeyeng** [comment]
Still broken for me. @VitaliyKurokhtin where can I email you my service name?

**Comment by VitaliyKurokhtin** [comment]
@joeyeng send me a mail at vitaliik@microsoft.com

**Comment by joeyeng** [comment]
Thanks, I'll check again on Monday. If it's still not updated I'll let you know. Have a good weekend!

**Comment by joeyeng** [comment]
@VitaliyKurokhtin I'm seeing "contentFormat" property missing for operation policies and "generatedSample" missing for operation response representation.

**Comment by VitaliyKurokhtin** [comment]
Only when you're getting list of policies, correct? If you fetch single policy it does return contentFormat.

**Comment by joeyeng** [comment]
@VitaliyKurokhtin Sorry, false alarm! I was looking at an ARM template I generated where I was retrieving single policy instead of the list.

**Comment by VitaliyKurokhtin** [comment]
@joeyeng ok. There is still an issue where querying for a list does not return contentFormat for each policy, and it will be fixed.

**Comment by joeyeng** [comment]
@VitaliyKurokhtin Any ETA on the contentFormat fix? Is there an open issue for this on github or somewhere else?

**Comment by VitaliyKurokhtin** [comment]
There is no public bugtracker for that. ETA is a couple of weeks since it's not a regression.
