### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by tobiasbettmann** [MLogdberg/APIManagementARMTemplateCreator#49]
Command: 

`Get-APIManagementTemplate -APIManagement API-MANAGEMENT-DEV -ResourceGroup API-WEU-D -SubscriptionId
xxxxe93f-xxxx-4f6c-xxxx-94376bexxxxx | Out-File c:\tmp\template.json`

Answer:
Get-APIManagementTemplate : Aggregation Exception thrown, Mindestens ein Fehler ist aufgetreten., first Exception
message is: Die Länge darf nicht kleiner als 0 (null) sein.
Parametername: length, for more information read the output file.
In Zeile:1 Zeichen:1
 Get-APIManagementTemplate -APIManagement API-MANAGEMENT-DEV -Reso ...
     CategoryInfo          : NotSpecified: (:) [Get-APIManagementTemplate], Exception
     FullyQualifiedErrorId : System.Exception,APIManagementTemplate.GeneratorCmdlet

In File:
`Aggregation exception thrown, se following exceptions for more information
Exception: Die Länge darf nicht kleiner als 0 (null) sein.
Parametername: length
   bei System.String.Substring(Int32 startIndex, Int32 length)
   bei APIManagementTemplate.TemplateGenerator.<GenerateTemplate>d__16.MoveNext()`

**Comment by MLogdberg** [comment]
Hi,
Seems like it's a substring behavior that is not doing well, do you have any posibility to debug it?

**Comment by nilshedstrom** [comment]
You need to send to send tokens to the commandlet before it will work. 
Do this with ”armclient token <subscriptionId>” | Get-ApiManagementTemplate .....”
Look at the Readme for complete examples

**Comment by satz5** [comment]
I'm also getting the same error. After adding armclient token also. Anyone found solution for this?

**Comment by nilshedstrom** [comment]
It is hard to know exactly what is wrong based on the information provided.
But the only substring operation in TemplateGenerator.GenerateTemplate is related to policy names. 
I tried to rewrite that code so that it can handle unexpected inputs in a better way.
This is included in pull request #60

**Comment by MLogdberg** [comment]
Also better error handling when not authorized added in pr #68

**Comment by MLogdberg** [comment]
Any updates on this? Otherwise I close it for now and you can create a new issue
