### ISSUE TITLE
'The resource 'Microsoft.ApiManagement/service/APIMINSTANCENAME/groups/administrators' is not defined in the template

### ISSUE THREAD

**Issue by koengillissen** [MLogdberg/APIManagementARMTemplateCreator#62]
Hi,

I am new to this module and I installed the PowerShell module and generated the APIM ARM template via following statement:
Get-APIManagementTemplate -APIFilters $filter -APIManagement $apimanagementname -ResourceGroup $resourcegroupname -SubscriptionId $Subscriptionid -TenantName $TenantName -ExportPIManagementInstance $false -ExportGroups $false | Out-File $TemplateFilePath

When I try to provision the ARM template I am getting the following error :
When I omit the -ExportGroups flag (which default value is true) it results in the same error.

Any ideas?

New-AzResourceGroupDeployment : 13:27:19 - Error: Code=InvalidTemplate; Message=Deployment template validation failed:
'The resource 'Microsoft.ApiManagement/service/APIMINSTANCENAME/groups/administrators' is not defined in the template. Ple
ase see https://aka.ms/arm-template for usage details.'.
At \deploy.ps1:112 char:5
+     New-AzResourceGroupDeployment -ResourceGroupName $resourceGroupNa ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDep
   loymentCmdlet

**Comment by MLogdberg** [comment]
Hi, this is an error due to added "DependsOn" to administrators witch is not needed (always there).
It should be fixed in the latest release that I did yesterday. Can you update and try again?

**Comment by koengillissen** [comment]
Thanks that fixed the issue. But is now failing one of the products:
Does this template only works if the APIM instance and resourcegroup don't exist yet?

New-AzResourceGroupDeployment : 14:32:17 - Resource Microsoft.ApiManagement/service/products 'APIMINSTANCE/unlimit
ed' failed with message '{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.ApiManagement/service/APIMINSTANCE' under resource group 'RESOURCEGROUP' was
 not found."
  }
}'
At deploy.ps1:112 char:5
+     New-AzResourceGroupDeployment -ResourceGroupName $resourceGroupNa ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDep
   loymentCmdlet

**Comment by MLogdberg** [comment]
Well, this message comes from not finding the APIM Instance.

Normaly we deploy to a instance that exists, creating an instance takes about 15 minutes.

**Comment by koengillissen** [comment]
Check, sorry for the late response! This one can be closed.
