### ISSUE TITLE
backend-id Policy substitution

### ISSUE THREAD

**Issue by neothoms** [MLogdberg/APIManagementARMTemplateCreator#65]
Hi, your tool is very interesting.
I tried to use it for my client project but I have found an issue or at least an interrogation.

How can we switch the backend-id in an operation policy when we have different environment ?

For the test I have done, the backend ID is stored in hard in the xml policy file.
Can we do a find and replace on the xml files and when is it best practice to make it ?

I also tried to use a Named Value variable in the policy. It works very well in azure apim but the arm creator tool fails with this error when there is a named value as backendid:
```

Write-APIManagementTemplates : Unexpected character encountered while parsing value: A. Path '', line 0, position 0.
Au caractère Ligne:1 : 346
+ ... ion $true | Write-APIManagementTemplates -OutputDirectory C:\temp\tem ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-APIManagementTemplates], JsonReaderException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonReaderException,APIManagementTemplate.WriteApiManagementTemplatesCmdlet
```

**Comment by MLogdberg** [comment]
Hi, sorry for late respons.
The tool extracts the backend, it parameterize it and you are able to change target in next enviornment bellow is a sample of how a backend of an function is updated with parameters to point to a new function.

Alos newly fixed a few issues around extractions that could be one of your errors.



`{
      "comments": "Generated for resource /subscriptions/9fe3a745-ef9d-489d-a2f5-29eb60ca357e/resourceGroups/api/providers/Microsoft.ApiManagement/service/mlogd/backends/product-query",
      "type": "Microsoft.ApiManagement/service/backends",
      "name": "[concat(parameters('service_mlogd_name'), '/' ,'product-query')]",
      "apiVersion": "2019-01-01",
      "properties": {
        "title": null,
        "description": "[parameters('product-query_siteName')]",
        "url": "[concat('https://',toLower(parameters('product-query_siteName')),'.azurewebsites.net/api')]",
        "protocol": "http",
        "resourceId": "[concat('https://management.azure.com/','subscriptions/',subscription().subscriptionId,'/resourceGroups/',parameters('product-query_resourceGroup'),'/providers/Microsoft.Web/sites/',parameters('product-query_siteName'))]",
        "credentials": {
          "query": {
            "code": [
              "{{product-query-key}}"
            ]
          }
        }
      },
      "resources": [],
      "dependsOn": []
    }`
