### ISSUE TITLE
property_xxxxx_name

### ISSUE THREAD

**Issue by danbyrne** [MLogdberg/APIManagementARMTemplateCreator#7]
In the ARM template there is a depends_on, which is:
        "[resourceId('Microsoft.ApiManagement/service/properties', parameters('service_TALAPIDev_name'),parameters('property_58db35e8e3f12111f4362527_name'))]",

However I cannot find any reference to this in the ARM template, and the template still seems to work if I remove this as a dependency...
Is this expected? Or has something changed, and there is supposed to be some API-based property (supposed to be a property for the name of the API?)

It looks to come from this code snipped:
                    if (!parametrizePropertiesOnly)
                    {

                        foreach (var apiName in identifiedProperty.apis)
                        {
                            var apiTemplate = template.resources.Where(rr => rr.Value<string>("name") == apiName).FirstOrDefault();
                            apiTemplate.Value<JArray>("dependsOn").Add($"[resourceId('Microsoft.ApiManagement/service/properties', parameters('service_{servicename}_name'),parameters('property_{propertyObject.Value<string>("name")}_name'))]");
                        }
                    }

But I havent spent the time to figure out what this is supposed to be doing, so I thought I'd reach out instead...

I've uploaded the sample ARM template for your review
[TALAPIDev_increment - Copy.zip](https://github.com/MLogdberg/APIManagementARMTemplateCreator/files/1847251/TALAPIDev_increment.-.Copy.zip)
Thanks

**Comment by twinpiloot** [comment]
The program is looking for properties inside the policy and generates a dependency for this property. This property is also a separate resource in the template. The dependency takes care that the property is created before the policy. This case, I noticed that the property name in the dependency is different from the name of the property resource ([concat(parameters('service_TALAPIDev_name'), '/' ,parameters('property_ServiceAccount.Password.RaiseLeadCallback_name'))]).

**Comment by twinpiloot** [comment]
Please try to change the line:
                            apiTemplate.Value<JArray>("dependsOn").Add($"[resourceId('Microsoft.ApiManagement/service/properties', parameters('service_{servicename}_name'),parameters('property_{propertyObject.Value<string>("name")}_name'))]");
into:
                            apiTemplate.Value<JArray>("dependsOn").Add($"[resourceId('Microsoft.ApiManagement/service/properties', parameters('service_{servicename}_name'), '{name}')]");
