### ISSUE TITLE
Exception message is: Value cannot be null. Parameter name: input

### ISSUE THREAD

**Issue by rabrahamOpti** [MLogdberg/APIManagementARMTemplateCreator#71]
When I run the following script:

```
armclient login
armclient token | Get-APIManagementTemplate -APIManagement myInstanceName -ResourceGroup myResourceGroup -SubscriptionId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -DebugOutPutFolder C:\Users\Me\Downloads | Out-File C:\Users\Me\Downloads\output-template.json
```

I get an error:

```
Get-APIManagementTemplate : Aggregation Exception thrown, One or more errors occurred., first Exception message is: Value cannot be null.
Parameter name: input, for more information read the output file.
At line:3 char:19
+ ... ent token | Get-APIManagementTemplate -APIManagement qa-opti-apim-por ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-APIManagementTemplate], Exception
    + FullyQualifiedErrorId : System.Exception,APIManagementTemplate.GeneratorCmdlet
```

I don't believe there's a parameter called input. Am I using this tool incorrectly?

**Comment by MLogdberg** [comment]
There are no paramter called input, need to see if there is something going on there

**Comment by gd201712** [comment]
I installed the "APIManagementTemplate" powershell module today and am getting the same error as rabrahamOpti above.

**Comment by JD-4810** [comment]
Same error.

**Comment by pfoolen** [comment]
I also have the same error

**Comment by MLogdberg** [comment]
Thanks for reporting and it seems like it's a problem when the parameter APIFilters is not supplied, work aroudn is just adding  -APIFilters ''

Adding work to fix this aswell

**Comment by JD-4810** [comment]
> Thanks for reporting and it seems like it's a problem when the parameter APIFilters is not supplied, work aroudn is just adding -APIFilters ''
> 
> Adding work to fix this aswell

Adding -APIFilters '' works perfectly. Thank you @MLogdberg :)

**Comment by MLogdberg** [comment]
Should be solved with PR #74

**Comment by pfoolen** [comment]
Now I get error "Aggregation Exception thrown, One or more errors occurred., first Exception message is: Object reference not set to an instance of an object."

**Comment by MLogdberg** [comment]
Could it be that you are not reciving any api's?

**Comment by pfoolen** [comment]
When using my own subscription I don't have this problem, so probalby there this is a uersrights issue

**Comment by MLogdberg** [comment]
Use tenant to point the login to the correct tenant

Med vänlig hälsning,
Mattias

Skickat från min iPhone

**Comment by MLogdberg** [comment]
Closing this since this is fixed now
