### ISSUE TITLE
Products with API acccess - Using a parameter that is not included in the ARM-Template

### ISSUE THREAD

**Issue by brynjarte** [MLogdberg/APIManagementARMTemplateCreator#78]
Trying to export API Management after creating a product with access to APIs.

The resouce type: Microsoft.ApiManagement/service/products/groups, are then dependent on the API, but the api name is parameterized with a parameter that don't exists.

`        {
          "comments": "Generated for resource /subscriptions/8a4a2401-585c-4a02-a2cb-30dbe70723d1/resourceGroups/nip-dev-rg/providers/Microsoft.ApiManagement/service/<name>/products/<groupName>/groups/administrators",
          "type": "Microsoft.ApiManagement/service/products/groups",
          "name": "[concat(parameters('service_<apim_name>'), '/', '<groupName>', '/', 'administrators')]",
          "apiVersion": "2019-01-01",
          "properties": {
            "displayName": "Administrators",
            "description": "Administrators is a built-in group. Its membership is managed by the system. Microsoft Azure subscription administrators fall into this group.",
            "builtIn": true,
            "type": "system",
            "externalId": null
          },
          "resources": [],
          "dependsOn": [
            "[resourceId('Microsoft.ApiManagement/service/products', parameters(service_<apim_name>), <groupName>)]"
          ]
        }
      ],
      "dependsOn": [
        "[resourceId('Microsoft.ApiManagement/service', parameters(service_<apim_name>))]",
        "[resourceId('Microsoft.ApiManagement/service/apis', parameters('service_<apim_name>), parameters(api_<apiName>))]"
      ]
`

The parameter **api_apiName** does not exist.

**Comment by twinpiloot** [comment]
Did you use ParametrizePropertiesOnly when generating the template?
If so, please check the latest version, because it might have been solved.

**Comment by MLogdberg** [comment]
Thanks fr reporting @brynjarte I've found where the issue is and are looking in to it

**Comment by MLogdberg** [comment]
I see that currently the export is exporting all api's in the same product.
Would expected behavior be that only the API's that are exported according to selection would be in the list of api's in the product? (I assume that is the case but jsut checking out)

**Comment by MLogdberg** [comment]
Check out #82 it has a fix for only adding api's that is inside the template.
@brynjarte

**Comment by brynjarte** [comment]
Hi,

Thank you for replying. Yes, I did use ParametrizePropertiesOnly. The issue is that the resource type "Microsoft.ApiManagement/service/products/groups"  is dependent on a API:

        "[resourceId('Microsoft.ApiManagement/service/apis', parameters('service_nip-dev-api-management_name'), parameters('api_banner_name'))]",

Where the parameter 'api_banner_name' is not created as a parameter.

**Comment by MLogdberg** [comment]
Okey, I think the PR #82 will solve this, can you test it out? @brynjarte

**Comment by brynjarte** [comment]
Perfect, it is working! Thank you!
