### ISSUE TITLE
The resource IfsGatewayFunctionApp is not defined in the template

### ISSUE THREAD

**Issue by twinpiloot** [MLogdberg/APIManagementARMTemplateCreator#79]
After the last update, my templates do not deploy with the following error:

The resource 'Microsoft.ApiManagement/service/myapim instance/apis/IfsGatewayFunctionApp/operations/5b695641f4c1942a581f51e6' is not defined in the template.

Seems that there is a dependency on an API that I do not have.

**Comment by MLogdberg** [comment]
hmm, I'll check that out

**Comment by MLogdberg** [comment]
Do you know where the dependency is, is it in the api, or on another operation or?

**Comment by twinpiloot** [comment]
Hi Mattias,

Thanks for responding so quickly.

Yes, it is this piece of new code in TemplateGenerator.cs. It was added by Gert Vloo and I also dropped him an email.
Point is that this dependency references an API called "IfsGatewayFunctionApp" and I do not have this API.

[cid:a5e2955d-e727-4caf-8fad-f077d6ff44ec]

Kind regards,

Martin
________________________________

**Comment by MLogdberg** [comment]
Found it, and a fix is on the way

**Comment by MLogdberg** [comment]
Fixed with PR #80

**Comment by MLogdberg** [comment]
Release to PowershellGallery is in the way and should be available in a few minutes

**Comment by MLogdberg** [comment]
Updated, please verify and if all let's close the issue :D

**Comment by twinpiloot** [comment]
I made another change, so ParametrizePropertiesOnly is working again. There might not be many users using this flag, but I still do.

**Comment by MLogdberg** [comment]
Thanks, I'll approve that aswell an I'll make sure to investigate changes better, sorry for this.
