### ISSUE TITLE
Support for backend arm template

### ISSUE THREAD

**Issue by Splaxi** [MLogdberg/APIManagementARMTemplateCreator#88]
When using the "Azure API Management DevOps Resource Kit", we get arm templates for all backends that are registered inside our APIM.

When using your module, we only get the policy files, with a reference to the backend.

Did I miss something or doesn't your module support backends exported into ARM templates?

**Comment by MLogdberg** [comment]
Hi @Splaxi  it's supported but since this tool aims for extracting only nessisary items, the backend need to be reference. Might be so that it's reference id a way that the tool is not recognizing?

**Comment by MLogdberg** [comment]
Might be the same as issue #100 ? solved in PR #102
