### ISSUE TITLE
Support for Powershell 7

### ISSUE THREAD

**Issue by SoucianceEqdamRashti** [MLogdberg/APIManagementARMTemplateCreator#89]
When running the powershell command in Powershell 7.X we encounter the following error:
![image](https://user-images.githubusercontent.com/6192200/102776323-d56c6580-438e-11eb-8707-28e4deb8ef58.png)

If we run the same command in Powershell 5 then it works fine.

Will there be support for Powershell 7?

**Comment by MLogdberg** [comment]
Hi, Sorry for late repsonse but should be solved now
